#!/bin/sh

# Compile the boot loader
clang -m64 -O2 -fshort-wchar -I ./kerninc -I ../Include -I ../Include/X64 -mcmodel=small -mno-red-zone -mno-stack-arg-probe -target x86_64-pc-mingw32 -Wall -Wno-address-of-packed-member -c boot.c
lld-link /dll /nodefaultlib /safeseh:no /machine:AMD64 /entry:efi_main boot.o /out:boot.dll
../fwimage/fwimage app boot.dll boot.efi

VARS="-Wall -Wno-address-of-packed-member -Wno-builtin-declaration-mismatch -D__XEN_INTERFACE_VERSION__=0x040601 -O2 -mno-red-zone -nostdinc -fno-stack-protector -I ./kerninc -I/usr/include/xen -pie -fno-zero-initialized-in-bss"

# Compile the kernel
gcc $VARS -c kernel_entry.S
gcc $VARS -c kernel.c
gcc $VARS -c basic_xen.c
gcc $VARS -c kernel_asm.S
gcc $VARS -c kernel_syscall.c
gcc $VARS -c printf.c
gcc $VARS -c fb.c
gcc $VARS -c ascii_font.c
gcc $VARS -c page_table.c
gcc $VARS -c apic.c
gcc $VARS -c exceptions.c
gcc $VARS -c gnttab.c
ld --oformat=binary -T ./kernel.lds -nostdlib -melf_x86_64 -pie kernel_entry.o page_table.o exceptions.o basic_xen.o apic.o kernel.o kernel_asm.o kernel_syscall.o printf.o fb.o ascii_font.o gnttab.o -o kernel

# Comple the user application
gcc -Wall -Wno-address-of-packed-member -Wno-builtin-declaration-mismatch -O2 -mno-red-zone -nostdinc -fno-stack-protector -I ./userinc -pie -fno-zero-initialized-in-bss -c user_entry.S
gcc -Wall -Wno-address-of-packed-member -Wno-builtin-declaration-mismatch -O2 -mno-red-zone -nostdinc -fno-stack-protector -I ./userinc -pie -fno-zero-initialized-in-bss -c user.c
ld --oformat=binary -T ./user.lds -nostdlib -melf_x86_64 -pie user_entry.o user.o -o user

# Create an ISO image (VBox)
rm -rf uefi_iso_image
mkdir -p uefi_iso_image/EFI/BOOT
cp boot.efi uefi_iso_image/EFI/BOOT/BOOTX64.EFI
cp kernel uefi_iso_image/EFI/BOOT/KERNEL
cp user uefi_iso_image/EFI/BOOT/USER
mkisofs -o boot.iso uefi_iso_image

# Create a FAT image (Xen Hypervisor)
rm -rf ./uefi_fat_mnt
mkdir ./uefi_fat_mnt
dd if=/dev/zero of=boot.img bs=1M count=100
mkfs.vfat ./boot.img
sudo mount -o loop ./boot.img ./uefi_fat_mnt
sudo mkdir -p ./uefi_fat_mnt/EFI/BOOT
sudo cp boot.efi ./uefi_fat_mnt/EFI/BOOT/BOOTX64.EFI
sudo cp kernel ./uefi_fat_mnt/EFI/BOOT/KERNEL
sudo cp user ./uefi_fat_mnt/EFI/BOOT/USER
sudo umount ./uefi_fat_mnt